ServerSignal/Controllers/RentalCarsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Rolling.Models;
using ServerSignal.Models;

namespace ServerSignal.Controllers
{
    [Authorize]
    public class RentalCarsController : Controller
    {
        private readonly ApplicationContextDb _db;
        
        public RentalCarsController(ApplicationContextDb db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cars = await _db.CarsRentalModels.ToListAsync();
            return View(cars);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CarsRentalModels carsRentalModels, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                using (var ms = new MemoryStream())
                {
                    await imageFile.CopyToAsync(ms);
                    carsRentalModels.Image = ms.ToArray();
                }
            }
            
            var rentalCar = new CarsRentalModels
            {
                Id = Guid.NewGuid(),
                Mark = carsRentalModels.Mark,
                Model = carsRentalModels.Model,
                Years = carsRentalModels.Years,
                Color = carsRentalModels.Color,
                HorsePower = carsRentalModels.HorsePower,
                Mileage = carsRentalModels.Mileage,
                Engine = carsRentalModels.Engine,
                Price = carsRentalModels.Price,
                City = carsRentalModels.City,
                Status = carsRentalModels.Status,
                Image = carsRentalModels.Image
            };
            
            await _db.CarsRentalModels.AddAsync(rentalCar);
            await _db.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var car = await _db.CarsRentalModels.FirstOrDefaultAsync(x => x.Id == id);

            if (car == null)
            {
                return RedirectToAction("Index");
            }

            var editCar = new CarsRentalModels
            {
                Id = car.Id,
                Mark = car.Mark,
                Model = car.Model,
                Years = car.Years,
                Color = car.Color,
                HorsePower = car.HorsePower,
                Mileage = car.Mileage,
                Engine = car.Engine,
                Price = car.Price,
                City = car.City,
                Status = car.Status,
            };

            return View("Edit", editCar);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CarsRentalModels carsRentalModels, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                using (var ms = new MemoryStream())
                {
                    await imageFile.CopyToAsync(ms);
                    carsRentalModels.Image = ms.ToArray();
                }
            }
            
            var sql = @"UPDATE CarsRentalModels SET Mark = @Mark, Model = @Model, Years = @Years, Color = @Color, HorsePower = @HorsePower, Mileage = @Mileage, Engine = @Engine, Price = @Price, City = @City, Status = @Status, Image = @Image WHERE Id = @Id";

            try
            {
                await _db.Database.ExecuteSqlRawAsync(sql, 
                    new SqlParameter("@Mark", carsRentalModels.Mark),
                    new SqlParameter("@Model", carsRentalModels.Model),
                    new SqlParameter("@Years", carsRentalModels.Years),
                    new SqlParameter("@Color", carsRentalModels.Color),
                    new SqlParameter("@HorsePower", carsRentalModels.HorsePower),
                    new SqlParameter("@Mileage", carsRentalModels.Mileage),
                    new SqlParameter("@Engine", carsRentalModels.Engine),
                    new SqlParameter("@Price", carsRentalModels.Price),
                    new SqlParameter("@City", carsRentalModels.City),
                    new SqlParameter("@Status", carsRentalModels.Status),
                    new SqlParameter("@Id", carsRentalModels.Id),
                    new SqlParameter("@Image", carsRentalModels.Image != null ? new SqlParameter("@Image", carsRentalModels.Image) : new SqlParameter("@Image", DBNull.Value))
                );
            }
            catch (DbUpdateException ex)
            {
                Console.WriteLine("Ошибка обновления данных. Попробуйте еще раз " + ex.Message);
                return View("Edit", carsRentalModels);
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CarsRentalModels carsRentalModels)
        {
            var existingCar = await _db.CarsRentalModels.FirstOrDefaultAsync(x => x.Id == carsRentalModels.Id);

            if (existingCar == null)
            {
                Console.WriteLine("Автомобиль не найден");
                return RedirectToAction("Index");
            }

            var sql = "DELETE FROM CarsRentalModels WHERE Id = @Id";
        
            try
            {
                var result = await _db.Database.ExecuteSqlRawAsync(sql, new SqlParameter("@Id", carsRentalModels.Id));
            
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }

                Console.WriteLine("Ошибка удаления данных. Запись не найдена или уже удалена.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Произошла ошибка при удалении. Попробуйте еще раз.");
            }

            return RedirectToAction("Index");
        }
    }
}

ServerSignal/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Rolling.Models;
using ServerSignal.Models;

namespace ServerSignal.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationContextDb _db;
        
        public UserController(ApplicationContextDb db)
        {
            _db = db;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cars = await _db.UserModels.ToListAsync();
            return View(cars);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _db.UserModels.FirstOrDefaultAsync(x => x.Id == id);

            if (user == null)
            {
                return RedirectToAction("Index");
            }

            var editUser = new UserModel
            {
                Id = user.Id,
                Name = user.Name,
                Email = user.Email,
                Age = user.Age,
                Level = user.Level,
                Permission = user.Permission,
            };

            return View("Edit", editUser);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserModel userModel)
        {
            var sql = @"UPDATE UserModels SET Name = @Name, Email = @Email, Age = @Age, Level = @Level, Permission = @Permission WHERE Id = @Id";

            try
            {
                await _db.Database.ExecuteSqlRawAsync(sql, 
                    new SqlParameter("@Name", userModel.Name),
                    new SqlParameter("@Email", userModel.Email),
                    new SqlParameter("@Age", userModel.Age),
                    new SqlParameter("@Level", userModel.Level),
                    new SqlParameter("@Permission", userModel.Permission),
                    new SqlParameter("@Id", userModel.Id)
                );
            }
            catch (DbUpdateException ex)
            {
                Console.WriteLine("Ошибка обновления данных. Попробуйте еще раз");
                return View("Edit", userModel);
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(UserModel userModel)
        {
            var existingUser = await _db.UserModels.FirstOrDefaultAsync(x => x.Id == userModel.Id);

            if (existingUser == null)
            {
                Console.WriteLine("Пользователь не найден");
                return RedirectToAction("Index");
            }

            var sql = "DELETE FROM UserModels WHERE Id = @Id";
        
            try
            {
                var result = await _db.Database.ExecuteSqlRawAsync(sql, new SqlParameter("@Id", userModel.Id));
            
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }

                Console.WriteLine("Ошибка удаления данных. Запись не найдена или уже удалена.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Произошла ошибка при удалении. Попробуйте еще раз.");
            }

            return RedirectToAction("Index");
        }
    }
}

ServerSignal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Server Rolling App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ServerSignal.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Control Panel</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RentalCars" asp-action="Index">Rental Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RentalCars" asp-action="Add">Add Rental Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Support Chat</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Server Rolling Application
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>